apiVersion: apps/v1
kind: Deployment
metadata:
  name: vizuo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vizuo
  template:
    metadata:
      labels:
        app: vizuo
    spec:
      containers:
      - name: vizuo-container
        image: vizuo:latest  
        imagePullPolicy: Never
        ports:
        - containerPort: 80
